export const projectsList = [
  {id: 1, src: '/rs_collage1.jpg', alt: 'Rose Sing Eastham and Associates, Inc. projects collage'},
  {id: 2, src: '/rs_collage2.jpg', alt: 'Rose Sing Eastham and Associates, Inc. projects collage'},
  {id: 3, src: '/rs1.jpg', alt: 'Rose Sing Eastham and Associates, Inc. project - pool lighting'},
  {id: 4, src: '/rs2.jpg', alt: 'Rose Sing Eastham and Associates, Inc. project - lake building'},
  {id: 5, src: '/rs3.jpg', alt: 'Rose Sing Eastham and Associates, Inc. project'},
  {id: 6, src: '/rs4.jpg', alt: 'Rose Sing Eastham and Associates, Inc. project'},
  {id: 7, src: '/rs5.jpg', alt: 'Rose Sing Eastham and Associates, Inc. project'},
  {id: 8, src: '/rs6.jpg', alt: 'Rose Sing Eastham and Associates, Inc. project'},
  {id: 9, src: '/rs7.jpg', alt: 'Rose Sing Eastham and Associates, Inc. project'},
  {id: 10, src: '/rs8.jpg', alt: 'Rose Sing Eastham and Associates, Inc. project'},
  {id: 11, src: '/rs9.jpg', alt: 'Rose Sing Eastham and Associates, Inc. project'},
  {id: 12, src: '/rs10.jpg', alt: 'Rose Sing Eastham and Associates, Inc. project'},
  {id: 13, src: '/rs11.jpg', alt: 'Rose Sing Eastham and Associates, Inc. project'},
  {id: 14, src: '/rs12.jpg', alt: 'Rose Sing Eastham and Associates, Inc. project'},
  {id: 15, src: '/rs13.jpg', alt: 'Rose Sing Eastham and Associates, Inc. project'},
  {id: 16, src: '/rs14.jpg', alt: 'Rose Sing Eastham and Associates, Inc. project'},
  {id: 17, src: '/tulare_cty_sheriff.JPG', alt: 'Tulare County Sheriff project'},
  {id: 18, src: '/visalia_fd.JPG', alt: 'Visalia Fire Department project'},
];
